using Domain_Models;
using Domain_Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Data_Access
{
    public class TechBlogDbContext : DbContext
    {
        public TechBlogDbContext(DbContextOptions options)
            : base(options) { }
        
        public DbSet<User> Users { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Star> Stars { get; set; }
        public DbSet<NewsLetter> NewsLetterUsers { get; set; }
        public DbSet<Image> Images { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            #region UserData
            modelBuilder.Entity<User>().HasData(new List<User>() {
                new User { Id = 1, FirstName = "Sibby", LastName = "Dufaire", Email = "sdufaire0@tuttocitta.it", Password = "lM1=QU8cC5", IsSubscribed = false },
                new User { Id = 2, FirstName = "Susanetta", LastName = "Kynman", Email = "skynman1@etsy.com", Password = "eD5=)=V=>", IsSubscribed = false },
                new User { Id = 3, FirstName = "Eva", LastName = "Sturge", Email = "esturge2@t.co", Password = "sV1@P.\\?!e", IsSubscribed = false },
                new User { Id = 4, FirstName = "Valma", LastName = "Wrate", Email = "vwrate3@mapquest.com", Password = "kA3`8!_RQ/dW7", IsSubscribed = false },
                new User { Id = 5, FirstName = "Val", LastName = "Sphinxe", Email = "vsphinxe4@psu.edu", Password = "hA0#1)e97M),<", IsSubscribed = false },
                new User { Id = 6, FirstName = "Kippy", LastName = "Fosbraey", Email = "kfosbraey5@engadget.com", Password = "yB2'74B.C#3v))", IsSubscribed = true },
                new User { Id = 7, FirstName = "Ralf", LastName = "Pinor", Email = "rpinor6@meetup.com", Password = "oN3\\QQnA6sZiwU", IsSubscribed = true },
                new User { Id = 8, FirstName = "Dyna", LastName = "Tiller", Email = "dtiller7@washington.edu", Password = "iK3!|tZD5C", IsSubscribed = false },
                new User { Id = 9, FirstName = "Mindy", LastName = "Wakeling", Email = "mwakeling8@google.nl", Password = "bV3!pYBIAeZ", IsSubscribed = false },
                new User { Id = 10, FirstName = "Clementia", LastName = "Gaywood", Email = "cgaywood9@technorati.com", Password = "mY4\\!FQ*PR", IsSubscribed = true },
                new User { Id = 11, FirstName = "Neill", LastName = "Nealy", Email = "nnealya@skyrock.com", Password = "gH8_Wnf#n$6)B#", IsSubscribed = false },
                new User { Id = 12, FirstName = "Shandie", LastName = "Whitlock", Email = "swhitlockb@delicious.com", Password = "vS8_vbUi_(", IsSubscribed = false },
                new User { Id = 13, FirstName = "Gav", LastName = "Huish", Email = "ghuishc@1und1.de", Password = "wM4\"UJm/#$7m6j4p", IsSubscribed = false },
                new User { Id = 14, FirstName = "Dom", LastName = "Gommery", Email = "dgommeryd@baidu.com", Password = "gT0%`7$uR)\"D", IsSubscribed = false },
                new User { Id = 15, FirstName = "Stanislaus", LastName = "Amdohr", Email = "samdohre@blogger.com", Password = "tT7{7`iDqn5Ro8", IsSubscribed = true },
                new User { Id = 16, FirstName = "Adan", LastName = "Briar", Email = "abriarf@topsy.com", Password = "vV5.%)+sT", IsSubscribed = true },
                new User { Id = 17, FirstName = "Wilbur", LastName = "Anshell", Email = "wanshellg@sohu.com", Password = "eP7{ol4Srl\"\"", IsSubscribed = false },
                new User { Id = 18, FirstName = "Ivy", LastName = "Menlow", Email = "imenlowh@virginia.edu", Password = "vG1\"6#fSi", IsSubscribed = false },
                new User { Id = 19, FirstName = "Hughie", LastName = "Brager", Email = "hbrageri@seesaa.net", Password = "hQ6(8m<B2y6e", IsSubscribed = true },
                new User { Id = 20, FirstName = "Ernestine", LastName = "Degoy", Email = "edegoyj@shareasale.com", Password = "mK3%\"{Kv", IsSubscribed = true },
                new User { Id = 21, FirstName = "Zacharia", LastName = "Rossiter", Email = "zrossiterk@earthlink.net", Password = "oZ6/5'+9~`KM6", IsSubscribed = true },
                new User { Id = 22, FirstName = "Dreddy", LastName = "McArte", Email = "dmcartel@nsw.gov.au", Password = "hP2%0R'@MQnc", IsSubscribed = false },
                new User { Id = 23, FirstName = "Egon", LastName = "Pauletti", Email = "epaulettim@reddit.com", Password = "aP0%!gsJLWBrgxx%", IsSubscribed = true },
                new User { Id = 24, FirstName = "Brandea", LastName = "Osler", Email = "boslern@statcounter.com", Password = "qV1<OzuRiiHl", IsSubscribed = true },
                new User { Id = 25, FirstName = "Valerie", LastName = "Vasilchenko", Email = "vvasilchenkoo@baidu.com", Password = "rF6%)vScY|_s", IsSubscribed = false },
                new User { Id = 26, FirstName = "Oby", LastName = "Buzin", Email = "obuzinp@imageshack.us", Password = "yF0+g2AFUrR\\Q\\{", IsSubscribed = false },
                new User { Id = 27, FirstName = "Sharai", LastName = "Lightewood", Email = "slightewoodq@theglobeandmail.com", Password = "yN9)YXQu_fYs>#", IsSubscribed = false },
                new User { Id = 28, FirstName = "Jakob", LastName = "Kings", Email = "jkingsr@dyndns.org", Password = "xU6=b%|1L", IsSubscribed = true },
                new User { Id = 29, FirstName = "Dana", LastName = "Harteley", Email = "dharteleys@usgs.gov", Password = "iU8\\2\\A.lr\"U/?h,", IsSubscribed = true },
                new User { Id = 30, FirstName = "Urbanus", LastName = "Duckett", Email = "uduckettt@rambler.ru", Password = "zP6\"s)QLu0", IsSubscribed = true },
                new User { Id = 31, FirstName = "Nita", LastName = "Gorch", Email = "ngorchu@vimeo.com", Password = "yI4*T9~CkMtC6", IsSubscribed = false },
                new User { Id = 32, FirstName = "Dulcy", LastName = "Taylo", Email = "dtaylov@businessinsider.com", Password = "gE9<ZbFofTR4", IsSubscribed = true },
                new User { Id = 33, FirstName = "Jennilee", LastName = "Greguoli", Email = "jgreguoliw@nhs.uk", Password = "oD0_N$Mm$ddf", IsSubscribed = true },
                new User { Id = 34, FirstName = "Ingra", LastName = "Ardron", Email = "iardronx@wunderground.com", Password = "aH6\\}Rv\"dWE@", IsSubscribed = false },
                new User { Id = 35, FirstName = "Rik", LastName = "Riccard", Email = "rriccardy@about.me", Password = "rQ6,Wq_='", IsSubscribed = true },
                new User { Id = 36, FirstName = "Selma", LastName = "Shillinglaw", Email = "sshillinglawz@alexa.com", Password = "cY5\"82_aj$jorFL", IsSubscribed = true },
                new User { Id = 37, FirstName = "Donia", LastName = "Northcott", Email = "dnorthcott10@people.com.cn", Password = "pR6\\O5E$C", IsSubscribed = false },
                new User { Id = 38, FirstName = "Jesse", LastName = "Oldman", Email = "joldman11@cocolog-nifty.com", Password = "mQ3\\8*A*R", IsSubscribed = false },
                new User { Id = 39, FirstName = "Tiffanie", LastName = "Woods", Email = "twoods12@noaa.gov", Password = "lG9*{{;bZf\"[3", IsSubscribed = false },
                new User { Id = 40, FirstName = "Waylin", LastName = "Cossar", Email = "wcossar13@mapquest.com", Password = "fK5\";U*U", IsSubscribed = false },
                new User { Id = 41, FirstName = "Phedra", LastName = "Tuxworth", Email = "ptuxworth14@alibaba.com", Password = "kU4#^S3h\\F", IsSubscribed = false },
                new User { Id = 42, FirstName = "Ronny", LastName = "Hofton", Email = "rhofton15@live.com", Password = "yN1'|5.8C?T$", IsSubscribed = true },
                new User { Id = 43, FirstName = "Isabella", LastName = "Niche", Email = "iniche16@cam.ac.uk", Password = "nE5$W&M#4b%3Yf", IsSubscribed = true },
                new User { Id = 44, FirstName = "Erin", LastName = "Hockaday", Email = "ehockaday17@google.com", Password = "iB5\"0Q%\\r", IsSubscribed = false },
                new User { Id = 45, FirstName = "Andrus", LastName = "Clindon", Email = "aclandon18@businessweek.com", Password = "eT7*~H}Gg7W", IsSubscribed = true },
                new User { Id = 46, FirstName = "Garret", LastName = "Wyllis", Email = "gwyllis19@drupal.org", Password = "jU4)5^A*}R#", IsSubscribed = true },
                new User { Id = 47, FirstName = "Adele", LastName = "Grimshaw", Email = "agrimshaw1a@woothemes.com", Password = "xF5=^(8F?D", IsSubscribed = false },
                new User { Id = 48, FirstName = "Vernice", LastName = "Prizeman", Email = "vprizeman1b@discovery.com", Password = "uE4)$9D^x", IsSubscribed = true },
                new User { Id = 49, FirstName = "Hal", LastName = "Falconer", Email = "hfalconer1c@si.edu", Password = "lY3&F)6@&@`B", IsSubscribed = true },
                new User { Id = 50, FirstName = "Mia", LastName = "Hughford", Email = "mhughford1d@deviantart.com", Password = "sA3&v%d^K=\\", IsSubscribed = false },
                    new User { Id = 51, FirstName = "Derrik", LastName = "Stansfield", Email = "dstansfield50@arizona.edu", Password = "rU3@NcA8", IsSubscribed = false },
                new User { Id = 52, FirstName = "Rog", LastName = "Fairbairn", Email = "rfairbairn51@w3.org", Password = "rN9]9S5!", IsSubscribed = false },
                new User { Id = 53, FirstName = "Nickie", LastName = "Vinsen", Email = "nvinsen52@zimbio.com", Password = "aE9H|D2?", IsSubscribed = true },
                new User { Id = 54, FirstName = "Ava", LastName = "Toffoloni", Email = "atoffoloni53@multiply.com", Password = "jO4w$H8*", IsSubscribed = true },
                new User { Id = 55, FirstName = "Felicia", LastName = "Mara", Email = "fmara54@hibu.com", Password = "kL1=SA3", IsSubscribed = false },
                new User { Id = 56, FirstName = "Bobby", LastName = "Underhill", Email = "bunderhill55@boston.com", Password = "jQ2.ME<1", IsSubscribed = false },
                new User { Id = 57, FirstName = "Lyndsey", LastName = "Amis", Email = "lamis56@reverbnation.com", Password = "xB6`!Y1Q", IsSubscribed = true },
                new User { Id = 58, FirstName = "Brigida", LastName = "Litt", Email = "blitt57@ihg.com", Password = "rQ3+94~>o", IsSubscribed = true },
                new User { Id = 59, FirstName = "Sofia", LastName = "Borrell", Email = "sborrell58@umn.edu", Password = "jL1$K4b#", IsSubscribed = false },
                new User { Id = 60, FirstName = "Anetta", LastName = "Dumphy", Email = "adumphy59@boston.com", Password = "pG2!M$J7", IsSubscribed = false },
                new User { Id = 61, FirstName = "Fionnula", LastName = "L'Estrange", Email = "flestrange60@fda.gov", Password = "vT3\\L(7g", IsSubscribed = false },
                new User { Id = 62, FirstName = "Ruthie", LastName = "Seaver", Email = "rseaver61@fda.gov", Password = "vA8=QnH)", IsSubscribed = true },
                new User { Id = 63, FirstName = "Herschel", LastName = "Founte", Email = "hfounte62@reverbnation.com", Password = "tT9$#F3", IsSubscribed = false },
                new User { Id = 64, FirstName = "Janek", LastName = "Cleverley", Email = "jcleverley63@va.gov", Password = "zR1*B6", IsSubscribed = false },
                new User { Id = 65, FirstName = "Hilda", LastName = "Eldon", Email = "heldon64@purevolume.com", Password = "qK3(CV4", IsSubscribed = true },
                new User { Id = 66, FirstName = "Vivyan", LastName = "Cavalli", Email = "vcavalli65@meetup.com", Password = "mU8}B8", IsSubscribed = false },
                new User { Id = 67, FirstName = "Daryl", LastName = "Bollom", Email = "dbollom66@hibu.com", Password = "fD5!P#C0", IsSubscribed = true },
                new User { Id = 68, FirstName = "Claudette", LastName = "Dixon", Email = "cdixon67@networksolutions.com", Password = "rJ2%&K8", IsSubscribed = false },
                new User { Id = 69, FirstName = "Marjory", LastName = "Skeene", Email = "mskeene68@mlb.com", Password = "qC4^^V0", IsSubscribed = true },
                new User { Id = 70, FirstName = "Shaylah", LastName = "Judd", Email = "sjudd69@purevolume.com", Password = "wH8%Z9A&", IsSubscribed = false },
                new User { Id = 71, FirstName = "Rodolfo", LastName = "Humbles", Email = "rhumbles70@marriott.com", Password = "yI3$D5", IsSubscribed = false },
                new User { Id = 72, FirstName = "Freddie", LastName = "Lodge", Email = "flodge71@about.com", Password = "sY2*R8V", IsSubscribed = true },
                new User { Id = 73, FirstName = "Hugo", LastName = "Yew", Email = "hyew72@disqus.com", Password = "qG5&T!9", IsSubscribed = true },
                new User { Id = 74, FirstName = "Bobby", LastName = "Yanchak", Email = "byanchak73@mapquest.com", Password = "pQ1@3V2", IsSubscribed = true },
                new User { Id = 75, FirstName = "Sasha", LastName = "Darcy", Email = "sdarcy74@disqus.com", Password = "dY8%K5", IsSubscribed = false },
                new User { Id = 76, FirstName = "Myrta", LastName = "Dodge", Email = "mdodge75@reverbnation.com", Password = "yT7|W3C", IsSubscribed = true },
                new User { Id = 77, FirstName = "Leah", LastName = "Heddon", Email = "lheddon76@hibu.com", Password = "xH9&N5", IsSubscribed = false },
                new User { Id = 78, FirstName = "Leela", LastName = "Decker", Email = "ldecker77@flickr.com", Password = "uD8*Z7", IsSubscribed = true },
                new User { Id = 79, FirstName = "Irma", LastName = "Leese", Email = "ileese78@parallels.com", Password = "sU4!B8", IsSubscribed = true },
                new User { Id = 80, FirstName = "Caitlyn", LastName = "Segrue", Email = "csegrue79@hubpages.com", Password = "sX5@Q3", IsSubscribed = true },
                new User { Id = 81, FirstName = "Stacy", LastName = "Pollett", Email = "spollett80@dagondesign.com", Password = "yR2%F6", IsSubscribed = false },
                new User { Id = 82, FirstName = "Waylon", LastName = "Chesman", Email = "wchesman81@nationalgeographic.com", Password = "xD8&K2", IsSubscribed = false },
                new User { Id = 83, FirstName = "Dory", LastName = "Whiteman", Email = "dwhiteman82@indiegogo.com", Password = "fF1^R7J", IsSubscribed = true },
                new User { Id = 84, FirstName = "Evie", LastName = "Drennan", Email = "edrennan83@blogtalkradio.com", Password = "cV2@D8^", IsSubscribed = false },
                new User { Id = 85, FirstName = "Lyndsey", LastName = "Dye", Email = "ldye84@hibu.com", Password = "tD4*M9", IsSubscribed = false },
                new User { Id = 86, FirstName = "Margret", LastName = "Penton", Email = "mpenton85@barnesandnoble.com", Password = "uT1]Q8#D", IsSubscribed = true },
                new User { Id = 87, FirstName = "Ilario", LastName = "Marzola", Email = "imarzola86@weebly.com", Password = "xU6+H4J", IsSubscribed = true },
                new User { Id = 88, FirstName = "Dewain", LastName = "Baker", Email = "dbaker87@last.fm", Password = "jF3@X5#D", IsSubscribed = false },
                new User { Id = 89, FirstName = "Vickie", LastName = "Dummigan", Email = "vdummigan88@un.org", Password = "gE9&X8!Y", IsSubscribed = false },
                new User { Id = 90, FirstName = "Alaric", LastName = "MacAskil", Email = "amacaskil89@disqus.com", Password = "sG2$M1", IsSubscribed = true },
                new User { Id = 91, FirstName = "Alberto", LastName = "Burmester", Email = "aburmester90@hibu.com", Password = "eG3%N8&", IsSubscribed = true },
                new User { Id = 92, FirstName = "Hedy", LastName = "Squeri", Email = "hsqueri91@japanpost.jp", Password = "mS8#D4A", IsSubscribed = true },
                new User { Id = 93, FirstName = "Marv", LastName = "Deeley", Email = "mdeeley92@berkeley.edu", Password = "hD2+P8#C", IsSubscribed = true },
                new User { Id = 94, FirstName = "Tristam", LastName = "Colby", Email = "tcolby93@hugedomains.com", Password = "bF4^S7", IsSubscribed = true },
                new User { Id = 95, FirstName = "Bobby", LastName = "Lunnon", Email = "blunnon94@flickr.com", Password = "nA3!Q7", IsSubscribed = false },
                new User { Id = 96, FirstName = "Herminia", LastName = "Tibbits", Email = "htibbits95@tumblr.com", Password = "oC7$M8", IsSubscribed = true },
                new User { Id = 97, FirstName = "Tammie", LastName = "Gonelle", Email = "tgonelle96@salon.com", Password = "dY1%X3@Q", IsSubscribed = true },
                new User { Id = 98, FirstName = "Corine", LastName = "Vinsen", Email = "cvinsen97@artisteer.com", Password = "mF2@W7#", IsSubscribed = true },
                new User { Id = 99, FirstName = "Sandro", LastName = "Goutorbe", Email = "sgoutorbe98@google.com", Password = "gJ8$Y2^", IsSubscribed = false },
                new User { Id = 100, FirstName = "Willie", LastName = "Trowell", Email = "wtrowell99@boston.com", Password = "cD9!Z8", IsSubscribed = false }
            });
            #endregion

            #region PostData
            modelBuilder.Entity<Post>().HasData(new List<Post>
{
    new Post { Id = 1, Title = "Best Tools for Web Development", Text = "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.", Description = "How AI is Revolutionizing Healthcare", UserId = 8, Tags = "innovation,internet", PostingTime = new DateTime(2024, 9, 15) },
    new Post { Id = 2, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "Vivamus vel nulla eget eros elementum pellentesque.", Description = "5 Tips for Effective Remote Work", UserId = 33, Tags = "gadgets,internet", PostingTime = new DateTime(2024, 9, 7) },
    new Post { Id = 3, Title = "Machine Learning Demystified", Text = "aliquet at", Description = "How AI is Revolutionizing Healthcare", UserId = 22, Tags = "innovation,software", PostingTime = new DateTime(2024, 4, 10) },
    new Post { Id = 4, Title = "Cloud Computing Simplified", Text = "hendrerit at", Description = "Blockchain Technology Explained", UserId = 31, Tags = "technology,coding", PostingTime = new DateTime(2020, 5, 3) },
    new Post { Id = 5, Title = "Tech Gadgets Every Geek Should Have", Text = "Duis ac nibh. Fusce lacus purus", Description = "5 Tips for Effective Remote Work", UserId = 83, Tags = "AI,gadgets", PostingTime = new DateTime(2022, 4, 29) },
    new Post { Id = 6, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "nisl. Aenean lectus.", Description = "How AI is Revolutionizing Healthcare", UserId = 39, Tags = "innovation,AI", PostingTime = new DateTime(2024, 2, 24) },
    new Post { Id = 7, Title = "The Impact of Big Data on Businesses", Text = "Vivamus metus arcu", Description = "Top 10 Tech Trends for 2021", UserId = 18, Tags = "cybersecurity,digital", PostingTime = new DateTime(2024, 3, 30) },
    new Post { Id = 8, Title = "Tech Gadgets Every Geek Should Have", Text = "pede.", Description = "How AI is Revolutionizing Healthcare", UserId = 48, Tags = "coding,innovation", PostingTime = new DateTime(2023, 10, 6) },
    new Post { Id = 9, Title = "Best Tools for Web Development", Text = "feugiat non", Description = "The Future of Cybersecurity", UserId = 41, Tags = "internet,innovation", PostingTime = new DateTime(2020, 1, 2) },
    new Post { Id = 10, Title = "How to Improve Your Coding Skills", Text = "lectus.", Description = "The Future of Cybersecurity", UserId = 9, Tags = "innovation,coding", PostingTime = new DateTime(2021, 1, 20) },
    new Post { Id = 11, Title = "The Future of Virtual Reality", Text = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.", Description = "Blockchain Technology Explained", UserId = 64, Tags = "technology,data", PostingTime = new DateTime(2022, 7, 9) },
    new Post { Id = 12, Title = "Top 10 Tech Trends for 2021", Text = "hendrerit at", Description = "How AI is Revolutionizing Healthcare", UserId = 84, Tags = "data,coding", PostingTime = new DateTime(2022, 8, 30) },
    new Post { Id = 13, Title = "The Future of Virtual Reality", Text = "Vivamus metus arcu", Description = "Blockchain Technology Explained", UserId = 88, Tags = "technology,gadgets", PostingTime = new DateTime(2023, 2, 2) },
    new Post { Id = 14, Title = "The Impact of Big Data on Businesses", Text = "nisl. Aenean lectus.", Description = "Blockchain Technology Explained", UserId = 64, Tags = "internet,innovation", PostingTime = new DateTime(2022, 3, 14) },
    new Post { Id = 15, Title = "Tech Gadgets Every Geek Should Have", Text = "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.", Description = "Top 10 Tech Trends for 2021", UserId = 8, Tags = "cybersecurity,internet", PostingTime = new DateTime(2022, 11, 10) },
    new Post { Id = 16, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "consectetuer adipiscing elit.", Description = "How AI is Revolutionizing Healthcare", UserId = 3, Tags = "gadgets,digital", PostingTime = new DateTime(2022, 6, 5) },
    new Post { Id = 17, Title = "Top 10 Tech Trends of 2021", Text = "tempus vel", Description = "How AI is Revolutionizing Healthcare", UserId = 94, Tags = "software,data", PostingTime = new DateTime(2020, 9, 11) },
    new Post { Id = 18, Title = "Top 10 Tech Trends for 2021", Text = "nisl.", Description = "5 Tips for Effective Remote Work", UserId = 71, Tags = "internet,technology", PostingTime = new DateTime(2020, 6, 14) },
    new Post { Id = 19, Title = "Cybersecurity Tips for Beginners", Text = "Vivamus vel nulla eget eros elementum pellentesque.", Description = "How AI is Revolutionizing Healthcare", UserId = 7, Tags = "gadgets,innovation", PostingTime = new DateTime(2022, 7, 27) },
    new Post { Id = 20, Title = "Best Tools for Web Development", Text = "turpis nec euismod scelerisque", Description = "5 Tips for Effective Remote Work", UserId = 18, Tags = "gadgets,cybersecurity", PostingTime = new DateTime(2022, 3, 19) },
    new Post { Id = 21, Title = "E-commerce Trends to Watch Out For", Text = "adipiscing molestie", Description = "Top 10 Tech Trends for 2021", UserId = 72, Tags = "innovation,internet", PostingTime = new DateTime(2024, 5, 9) },
    new Post { Id = 22, Title = "How AI is Revolutionizing the Tech Industry", Text = "vulputate vitae", Description = "How AI is Revolutionizing Healthcare", UserId = 64, Tags = "gadgets,software", PostingTime = new DateTime(2022, 1, 21) },
    new Post { Id = 23, Title = "How AI is Revolutionizing the Tech Industry", Text = "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.", Description = "How AI is Revolutionizing Healthcare", UserId = 93, Tags = "AI,software", PostingTime = new DateTime(2023, 6, 15) },
    new Post { Id = 24, Title = "Cybersecurity Tips for Beginners", Text = "lectus.", Description = "Blockchain Technology Explained", UserId = 5, Tags = "cybersecurity,data", PostingTime = new DateTime(2022, 1, 2) },
    new Post { Id = 25, Title = "How to Improve Your Coding Skills", Text = "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.", Description = "The Future of Cybersecurity", UserId = 3, Tags = "software,cybersecurity", PostingTime = new DateTime(2022, 7, 24) },
    new Post { Id = 26, Title = "The Future of Virtual Reality", Text = "hendrerit at", Description = "How AI is Revolutionizing Healthcare", UserId = 33, Tags = "coding,technology", PostingTime = new DateTime(2024, 1, 10) },
    new Post { Id = 27, Title = "The Future of Virtual Reality", Text = "Duis ac nibh. Fusce lacus purus", Description = "5 Tips for Effective Remote Work", UserId = 53, Tags = "software,coding", PostingTime = new DateTime(2023, 2, 20) },
    new Post { Id = 28, Title = "Top 10 Tech Trends of 2021", Text = "Duis ac nibh. Fusce lacus purus", Description = "The Future of Cybersecurity", UserId = 36, Tags = "internet,AI", PostingTime = new DateTime(2024, 7, 14) },
    new Post { Id = 29, Title = "Innovations in Mobile App Development", Text = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.", Description = "The Future of Cybersecurity", UserId = 66, Tags = "digital,innovation", PostingTime = new DateTime(2021, 8, 18) },
    new Post { Id = 30, Title = "Innovations in Mobile App Development", Text = "hendrerit at", Description = "The Future of Cybersecurity", UserId = 48, Tags = "cybersecurity,technology", PostingTime = new DateTime(2024, 3, 10) },
    new Post { Id = 31, Title = "Social Media Marketing Techniques", Text = "nisl. Aenean lectus.", Description = "Top 10 Tech Trends for 2021", UserId = 7, Tags = "internet,technology", PostingTime = new DateTime(2020, 2, 19) },
    new Post { Id = 32, Title = "Digital Marketing Strategies for Success", Text = "hendrerit at", Description = "Blockchain Technology Explained", UserId = 49, Tags = "cybersecurity,software", PostingTime = new DateTime(2024, 2, 1) },
    new Post { Id = 33, Title = "Machine Learning Demystified", Text = "Vivamus metus arcu", Description = "Blockchain Technology Explained", UserId = 59, Tags = "AI,coding", PostingTime = new DateTime(2024, 3, 27) },
    new Post { Id = 34, Title = "Cybersecurity Tips for Beginners", Text = "nisl. Aenean lectus.", Description = "Blockchain Technology Explained", UserId = 8, Tags = "gadgets,internet", PostingTime = new DateTime(2020, 5, 5) },
    new Post { Id = 35, Title = "The Future of Virtual Reality", Text = "hendrerit at", Description = "How AI is Revolutionizing Healthcare", UserId = 40, Tags = "gadgets,coding", PostingTime = new DateTime(2022, 6, 24) },
    new Post { Id = 36, Title = "Data Privacy in the Digital Age", Text = "nisl. Aenean lectus.", Description = "Top 10 Tech Trends for 2021", UserId = 78, Tags = "digital,data", PostingTime = new DateTime(2024, 7, 1) },
    new Post { Id = 37, Title = "Machine Learning Demystified", Text = "vulputate vitae", Description = "The Future of Cybersecurity", UserId = 12, Tags = "cybersecurity,internet", PostingTime = new DateTime(2020, 5, 2) },
    new Post { Id = 38, Title = "Tech Gadgets Every Geek Should Have", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "How AI is Revolutionizing Healthcare", UserId = 95, Tags = "digital,innovation", PostingTime = new DateTime(2024, 7, 11) },
    new Post { Id = 39, Title = "Social Media Marketing Techniques", Text = "tincidunt eget", Description = "Blockchain Technology Explained", UserId = 49, Tags = "cybersecurity,data", PostingTime = new DateTime(2021, 8, 9) },
    new Post { Id = 40, Title = "Best Tools for Web Development", Text = "Integer pede justo", Description = "5 Tips for Effective Remote Work", UserId = 95, Tags = "internet,technology", PostingTime = new DateTime(2023, 9, 24) },
    new Post { Id = 41, Title = "SEO Strategies for Small Businesses", Text = "vulputate vitae", Description = "Top 10 Tech Trends for 2021", UserId = 63, Tags = "internet,innovation", PostingTime = new DateTime(2020, 6, 3) },
    new Post { Id = 42, Title = "Best Tools for Web Development", Text = "nisl.", Description = "Top 10 Tech Trends for 2021", UserId = 75, Tags = "innovation,AI", PostingTime = new DateTime(2024, 2, 22) },
    new Post { Id = 43, Title = "The Impact of Big Data on Businesses", Text = "Morbi quis tortor id nulla ultrices aliquet.", Description = "The Future of Cybersecurity", UserId = 29, Tags = "innovation,internet", PostingTime = new DateTime(2021, 12, 3) },
    new Post { Id = 44, Title = "Social Media Marketing Techniques", Text = "vulputate vitae", Description = "5 Tips for Effective Remote Work", UserId = 36, Tags = "digital,software", PostingTime = new DateTime(2024, 2, 6) },
    new Post { Id = 45, Title = "The Power of Influencer Marketing", Text = "hendrerit at", Description = "The Future of Cybersecurity", UserId = 3, Tags = "coding,cybersecurity", PostingTime = new DateTime(2023, 6, 15) },
    new Post { Id = 46, Title = "Tech Gadgets Every Geek Should Have", Text = "vulputate vitae", Description = "The Future of Cybersecurity", UserId = 41, Tags = "cybersecurity,innovation", PostingTime = new DateTime(2022, 5, 1) },
    new Post { Id = 47, Title = "The Power of Influencer Marketing", Text = "Morbi quis tortor id nulla ultrices aliquet.", Description = "Top 10 Tech Trends for 2021", UserId = 77, Tags = "innovation,coding", PostingTime = new DateTime(2023, 3, 19) },
    new Post { Id = 48, Title = "E-commerce Trends to Watch Out For", Text = "vulputate vitae", Description = "Blockchain Technology Explained", UserId = 73, Tags = "cybersecurity,software", PostingTime = new DateTime(2022, 12, 20) },
    new Post { Id = 49, Title = "The Future of Virtual Reality", Text = "nisl. Aenean lectus.", Description = "Blockchain Technology Explained", UserId = 24, Tags = "digital,AI", PostingTime = new DateTime(2021, 6, 14) },
    new Post { Id = 50, Title = "E-commerce Trends to Watch Out For", Text = "tincidunt eget", Description = "5 Tips for Effective Remote Work", UserId = 55, Tags = "data,software", PostingTime = new DateTime(2023, 5, 29) },
    new Post { Id = 51, Title = "The Power of Influencer Marketing", Text = "lacinia eget", Description = "Blockchain Technology Explained", UserId = 64, Tags = "internet,technology", PostingTime = new DateTime(2023, 9, 23) },
    new Post { Id = 52, Title = "Blockchain Technology Explained", Text = "nisl.", Description = "How AI is Revolutionizing Healthcare", UserId = 14, Tags = "digital,internet", PostingTime = new DateTime(2020, 4, 19) },
    new Post { Id = 53, Title = "How to Improve Your Coding Skills", Text = "Morbi quis tortor id nulla ultrices aliquet.", Description = "Top 10 Tech Trends for 2021", UserId = 1, Tags = "internet,software", PostingTime = new DateTime(2020, 5, 12) },
    new Post { Id = 54, Title = "How to Improve Your Coding Skills", Text = "lectus.", Description = "5 Tips for Effective Remote Work", UserId = 20, Tags = "cybersecurity,internet", PostingTime = new DateTime(2021, 8, 23) },
    new Post { Id = 55, Title = "Tech Gadgets Every Geek Should Have", Text = "tempus vel", Description = "Blockchain Technology Explained", UserId = 19, Tags = "internet,software", PostingTime = new DateTime(2024, 7, 5) },
    new Post { Id = 56, Title = "Cybersecurity Tips for Beginners", Text = "lacinia eget", Description = "Top 10 Tech Trends for 2021", UserId = 47, Tags = "technology,data", PostingTime = new DateTime(2021, 10, 7) },
    new Post { Id = 57, Title = "The Power of Influencer Marketing", Text = "vulputate vitae", Description = "5 Tips for Effective Remote Work", UserId = 21, Tags = "internet,data", PostingTime = new DateTime(2022, 3, 22) },
    new Post { Id = 58, Title = "How AI is Revolutionizing the Tech Industry", Text = "vulputate vitae", Description = "The Future of Cybersecurity", UserId = 5, Tags = "data,software", PostingTime = new DateTime(2024, 3, 28) },
    new Post { Id = 59, Title = "The Power of Influencer Marketing", Text = "pretium quis", Description = "The Future of Cybersecurity", UserId = 64, Tags = "gadgets,innovation", PostingTime = new DateTime(2024, 4, 25) },
    new Post { Id = 60, Title = "The Impact of Big Data on Businesses", Text = "nascetur ridiculus mus.", Description = "The Future of Cybersecurity", UserId = 54, Tags = "internet,AI", PostingTime = new DateTime(2020, 11, 21) },
    new Post { Id = 61, Title = "Social Media Marketing Techniques", Text = "nascetur ridiculus mus.", Description = "How AI is Revolutionizing Healthcare", UserId = 43, Tags = "internet,technology", PostingTime = new DateTime(2023, 5, 26) },
    new Post { Id = 62, Title = "Top 10 Tech Trends for 2021", Text = "lectus.", Description = "How AI is Revolutionizing Healthcare", UserId = 60, Tags = "coding,digital", PostingTime = new DateTime(2020, 8, 8) },
    new Post { Id = 63, Title = "Cybersecurity in the Digital Age", Text = "aliquet at", Description = "The Future of Cybersecurity", UserId = 58, Tags = "internet,technology", PostingTime = new DateTime(2022, 7, 22) },
    new Post { Id = 64, Title = "How to Improve Your Coding Skills", Text = "adipiscing molestie", Description = "Blockchain Technology Explained", UserId = 7, Tags = "AI,digital", PostingTime = new DateTime(2023, 6, 23) },
    new Post { Id = 65, Title = "Tech Gadgets Every Geek Should Have", Text = "nisl. Aenean lectus.", Description = "Top 10 Tech Trends for 2021", UserId = 99, Tags = "gadgets,internet", PostingTime = new DateTime(2022, 4, 19) },
    new Post { Id = 66, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "nisl.", Description = "Blockchain Technology Explained", UserId = 70, Tags = "coding,innovation", PostingTime = new DateTime(2021, 12, 9) },
    new Post { Id = 67, Title = "Digital Marketing Strategies for Success", Text = "turpis nec euismod scelerisque", Description = "The Future of Cybersecurity", UserId = 26, Tags = "data,internet", PostingTime = new DateTime(2021, 7, 17) },
    new Post { Id = 68, Title = "Data Privacy in the Digital Age", Text = "pede.", Description = "The Future of Cybersecurity", UserId = 12, Tags = "AI,internet", PostingTime = new DateTime(2022, 1, 25) },
    new Post { Id = 69, Title = "How to Improve Your Coding Skills", Text = "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.", Description = "The Future of Cybersecurity", UserId = 94, Tags = "AI,coding", PostingTime = new DateTime(2021, 5, 30) },
    new Post { Id = 70, Title = "How to Improve Your Coding Skills", Text = "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu", Description = "The Future of Cybersecurity", UserId = 81, Tags = "coding,technology", PostingTime = new DateTime(2020, 4, 19) },
    new Post { Id = 71, Title = "Tech Gadgets Every Geek Should Have", Text = "Vivamus metus arcu", Description = "The Future of Cybersecurity", UserId = 78, Tags = "data,technology", PostingTime = new DateTime(2022, 7, 16) },
    new Post { Id = 72, Title = "SEO Strategies for Small Businesses", Text = "nisl.", Description = "The Future of Cybersecurity", UserId = 3, Tags = "AI,technology", PostingTime = new DateTime(2022, 2, 26) },
    new Post { Id = 73, Title = "The Impact of Big Data on Businesses", Text = "Vivamus metus arcu", Description = "The Future of Cybersecurity", UserId = 10, Tags = "technology,software", PostingTime = new DateTime(2020, 3, 8) },
    new Post { Id = 74, Title = "SEO Strategies for Small Businesses", Text = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.", Description = "Blockchain Technology Explained", UserId = 97, Tags = "technology,coding", PostingTime = new DateTime(2022, 12, 26) },
    new Post { Id = 75, Title = "Top 10 Tech Trends of 2021", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "5 Tips for Effective Remote Work", UserId = 37, Tags = "cybersecurity,AI", PostingTime = new DateTime(2022, 1, 26) },
    new Post { Id = 76, Title = "Tech Gadgets Every Geek Should Have", Text = "hendrerit at", Description = "The Future of Cybersecurity", UserId = 12, Tags = "AI,innovation", PostingTime = new DateTime(2024, 1, 5) },
    new Post { Id = 77, Title = "SEO Strategies for Small Businesses", Text = "Duis ac nibh. Fusce lacus purus", Description = "Top 10 Tech Trends for 2021", UserId = 38, Tags = "cybersecurity,gadgets", PostingTime = new DateTime(2020, 12, 5) },
    new Post { Id = 78, Title = "The Impact of Big Data on Businesses", Text = "adipiscing molestie", Description = "How AI is Revolutionizing Healthcare", UserId = 96, Tags = "coding,technology", PostingTime = new DateTime(2023, 6, 8) },
    new Post { Id = 79, Title = "Creating Engaging Content for Your Blog", Text = "tempus vel", Description = "Top 10 Tech Trends for 2021", UserId = 65, Tags = "technology,AI", PostingTime = new DateTime(2024, 2, 16) },
    new Post { Id = 80, Title = "The Impact of Big Data on Businesses", Text = "Vivamus vel nulla eget eros elementum pellentesque.", Description = "Top 10 Tech Trends for 2021", UserId = 25, Tags = "software,technology", PostingTime = new DateTime(2022, 11, 28) },
    new Post { Id = 81, Title = "Cybersecurity in the Digital Age", Text = "turpis nec euismod scelerisque", Description = "5 Tips for Effective Remote Work", UserId = 33, Tags = "coding,AI", PostingTime = new DateTime(2021, 2, 9) },
    new Post { Id = 82, Title = "Tech Gadgets Every Geek Should Have", Text = "Duis ac nibh. Fusce lacus purus", Description = "The Future of Cybersecurity", UserId = 93, Tags = "digital,coding", PostingTime = new DateTime(2020, 10, 11) },
    new Post { Id = 83, Title = "Digital Marketing Strategies for Success", Text = "nisl.", Description = "5 Tips for Effective Remote Work", UserId = 95, Tags = "data,gadgets", PostingTime = new DateTime(2020, 12, 26) },
    new Post { Id = 84, Title = "Data Privacy in the Digital Age", Text = "consectetuer adipiscing elit.", Description = "How AI is Revolutionizing Healthcare", UserId = 13, Tags = "coding,technology", PostingTime = new DateTime(2023, 3, 3) },
    new Post { Id = 85, Title = "Cybersecurity Tips for Beginners", Text = "lectus.", Description = "Top 10 Tech Trends for 2021", UserId = 43, Tags = "internet,gadgets", PostingTime = new DateTime(2021, 3, 14) },
    new Post { Id = 86, Title = "The Power of Influencer Marketing", Text = "Vivamus metus arcu", Description = "Top 10 Tech Trends for 2021", UserId = 93, Tags = "coding,innovation", PostingTime = new DateTime(2022, 3, 12) },
    new Post { Id = 87, Title = "Top 10 Tech Trends of 2021", Text = "consectetuer adipiscing elit.", Description = "How AI is Revolutionizing Healthcare", UserId = 80, Tags = "cybersecurity,digital", PostingTime = new DateTime(2020, 7, 16) },
    new Post { Id = 88, Title = "How to Improve Your Coding Skills", Text = "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu", Description = "Top 10 Tech Trends for 2021", UserId = 90, Tags = "coding,gadgets", PostingTime = new DateTime(2020, 11, 10) },
    new Post { Id = 89, Title = "The Power of Influencer Marketing", Text = "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.", Description = "Blockchain Technology Explained", UserId = 100, Tags = "technology,cybersecurity", PostingTime = new DateTime(2023, 9, 17) },
    new Post { Id = 90, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "turpis nec euismod scelerisque", Description = "How AI is Revolutionizing Healthcare", UserId = 11, Tags = "AI,technology", PostingTime = new DateTime(2023, 4, 24) },
    new Post { Id = 91, Title = "Tech Gadgets Every Geek Should Have", Text = "hendrerit at", Description = "The Future of Cybersecurity", UserId = 92, Tags = "innovation,gadgets", PostingTime = new DateTime(2022, 1, 8) },
    new Post { Id = 92, Title = "The Power of Influencer Marketing", Text = "tempus vel", Description = "Blockchain Technology Explained", UserId = 28, Tags = "software,gadgets", PostingTime = new DateTime(2021, 1, 11) },
    new Post { Id = 93, Title = "E-commerce Trends to Watch Out For", Text = "pede.", Description = "5 Tips for Effective Remote Work", UserId = 24, Tags = "coding,technology", PostingTime = new DateTime(2022, 6, 17) },
    new Post { Id = 94, Title = "Cloud Computing Simplified", Text = "lectus.", Description = "Blockchain Technology Explained", UserId = 6, Tags = "cybersecurity,digital", PostingTime = new DateTime(2023, 12, 20) },
    new Post { Id = 95, Title = "Data Privacy in the Digital Age", Text = "aliquet at", Description = "The Future of Cybersecurity", UserId = 43, Tags = "innovation,AI", PostingTime = new DateTime(2022, 1, 28) },
    new Post { Id = 96, Title = "The Power of Influencer Marketing", Text = "turpis nec euismod scelerisque", Description = "The Future of Cybersecurity", UserId = 15, Tags = "coding,technology", PostingTime = new DateTime(2021, 1, 3) },
    new Post { Id = 97, Title = "Machine Learning Demystified", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "Top 10 Tech Trends for 2021", UserId = 24, Tags = "AI,cybersecurity", PostingTime = new DateTime(2020, 12, 13) },
    new Post { Id = 98, Title = "Social Media Marketing Techniques", Text = "lectus.", Description = "5 Tips for Effective Remote Work", UserId = 10, Tags = "technology,digital", PostingTime = new DateTime(2021, 1, 31) },
    new Post { Id = 99, Title = "The Power of Influencer Marketing", Text = "nisl.", Description = "The Future of Cybersecurity", UserId = 59, Tags = "cybersecurity,innovation", PostingTime = new DateTime(2022, 1, 25) },
    new Post { Id = 100, Title = "Top 10 Tech Trends for 2021", Text = "vitae mattis nibh ligula nec sem.", Description = "5 Tips for Effective Remote Work", UserId = 16, Tags = "innovation,technology", PostingTime = new DateTime(2023, 7, 8) },
    new Post { Id = 101, Title = "Cybersecurity in the Digital Age", Text = "consectetuer adipiscing elit.", Description = "The Future of Cybersecurity", UserId = 7, Tags = "internet,software", PostingTime = new DateTime(2023, 12, 11) },
    new Post { Id = 102, Title = "Best Tools for Web Development", Text = "adipiscing molestie", Description = "5 Tips for Effective Remote Work", UserId = 6, Tags = "innovation,software", PostingTime = new DateTime(2020, 7, 4) },
    new Post { Id = 103, Title = "How to Improve Your Coding Skills", Text = "feugiat non", Description = "Top 10 Tech Trends for 2021", UserId = 67, Tags = "digital,software", PostingTime = new DateTime(2020, 9, 20) },
    new Post { Id = 104, Title = "Social Media Marketing Techniques", Text = "vulputate vitae", Description = "Blockchain Technology Explained", UserId = 78, Tags = "technology,cybersecurity", PostingTime = new DateTime(2023, 3, 28) },
    new Post { Id = 105, Title = "Cybersecurity in the Digital Age", Text = "pede.", Description = "How AI is Revolutionizing Healthcare", UserId = 25, Tags = "software,data", PostingTime = new DateTime(2022, 7, 24) },
    new Post { Id = 106, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "lectus.", Description = "Blockchain Technology Explained", UserId = 26, Tags = "innovation,software", PostingTime = new DateTime(2022, 12, 10) },
    new Post { Id = 107, Title = "How to Improve Your Coding Skills", Text = "tincidunt eget", Description = "The Future of Cybersecurity", UserId = 87, Tags = "technology,gadgets", PostingTime = new DateTime(2021, 3, 28) },
    new Post { Id = 108, Title = "How to Improve Your Coding Skills", Text = "Morbi quis tortor id nulla ultrices aliquet.", Description = "Top 10 Tech Trends for 2021", UserId = 33, Tags = "gadgets,AI", PostingTime = new DateTime(2024, 5, 5) },
    new Post { Id = 109, Title = "Data Privacy in the Digital Age", Text = "nisl.", Description = "How AI is Revolutionizing Healthcare", UserId = 60, Tags = "cybersecurity,digital", PostingTime = new DateTime(2023, 2, 14) },
    new Post { Id = 110, Title = "How to Improve Your Coding Skills", Text = "nisl.", Description = "5 Tips for Effective Remote Work", UserId = 83, Tags = "software,technology", PostingTime = new DateTime(2021, 7, 13) },
    new Post { Id = 111, Title = "Best Tools for Web Development", Text = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.", Description = "The Future of Cybersecurity", UserId = 12, Tags = "coding,internet", PostingTime = new DateTime(2021, 9, 9) },
    new Post { Id = 112, Title = "The Impact of Big Data on Businesses", Text = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.", Description = "How AI is Revolutionizing Healthcare", UserId = 76, Tags = "coding,data", PostingTime = new DateTime(2024, 5, 16) },
    new Post { Id = 113, Title = "Tech Gadgets Every Geek Should Have", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "5 Tips for Effective Remote Work", UserId = 72, Tags = "AI,gadgets", PostingTime = new DateTime(2022, 9, 20) },
    new Post { Id = 114, Title = "Blockchain Technology Explained", Text = "Vivamus vel nulla eget eros elementum pellentesque.", Description = "How AI is Revolutionizing Healthcare", UserId = 4, Tags = "software,internet", PostingTime = new DateTime(2024, 2, 5) },
    new Post { Id = 115, Title = "Tech Gadgets Every Geek Should Have", Text = "consectetuer adipiscing elit.", Description = "Blockchain Technology Explained", UserId = 36, Tags = "data,software", PostingTime = new DateTime(2020, 10, 18) },
    new Post { Id = 116, Title = "How AI is Revolutionizing the Tech Industry", Text = "pede.", Description = "5 Tips for Effective Remote Work", UserId = 7, Tags = "AI,data", PostingTime = new DateTime(2022, 11, 23) },
    new Post { Id = 117, Title = "Tech Gadgets Every Geek Should Have", Text = "Morbi quis tortor id nulla ultrices aliquet.", Description = "5 Tips for Effective Remote Work", UserId = 58, Tags = "data,gadgets", PostingTime = new DateTime(2024, 2, 19) },
    new Post { Id = 118, Title = "Machine Learning Demystified", Text = "Duis ac nibh. Fusce lacus purus", Description = "The Future of Cybersecurity", UserId = 100, Tags = "digital,AI", PostingTime = new DateTime(2022, 12, 1) },
    new Post { Id = 119, Title = "Blockchain Technology Explained", Text = "In blandit ultrices enim. Lorem ipsum dolor sit amet", Description = "How AI is Revolutionizing Healthcare", UserId = 84, Tags = "internet,software", PostingTime = new DateTime(2022, 3, 16) },
    new Post { Id = 120, Title = "How to Improve Your Coding Skills", Text = "pretium quis", Description = "How AI is Revolutionizing Healthcare", UserId = 47, Tags = "gadgets,cybersecurity", PostingTime = new DateTime(2022, 11, 4) },
    new Post { Id = 121, Title = "The Future of Virtual Reality", Text = "nascetur ridiculus mus.", Description = "How AI is Revolutionizing Healthcare", UserId = 96, Tags = "coding,internet", PostingTime = new DateTime(2020, 10, 3) },
    new Post { Id = 122, Title = "E-commerce Trends to Watch Out For", Text = "adipiscing molestie", Description = "The Future of Cybersecurity", UserId = 44, Tags = "coding,cybersecurity", PostingTime = new DateTime(2024, 1, 20) },
    new Post { Id = 123, Title = "Data Privacy in the Digital Age", Text = "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu", Description = "5 Tips for Effective Remote Work", UserId = 95, Tags = "digital,AI", PostingTime = new DateTime(2023, 6, 27) },
    new Post { Id = 124, Title = "How AI is Revolutionizing the Tech Industry", Text = "lectus.", Description = "How AI is Revolutionizing Healthcare", UserId = 27, Tags = "digital,technology", PostingTime = new DateTime(2022, 10, 25) },
    new Post { Id = 125, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "adipiscing molestie", Description = "Blockchain Technology Explained", UserId = 83, Tags = "innovation,digital", PostingTime = new DateTime(2021, 4, 12) },
    new Post { Id = 126, Title = "The Power of Influencer Marketing", Text = "tempus vel", Description = "How AI is Revolutionizing Healthcare", UserId = 51, Tags = "software,gadgets", PostingTime = new DateTime(2020, 10, 15) },
    new Post { Id = 127, Title = "Tech Gadgets Every Geek Should Have", Text = "Vivamus metus arcu", Description = "The Future of Cybersecurity", UserId = 40, Tags = "cybersecurity,coding", PostingTime = new DateTime(2021, 5, 14) },
    new Post { Id = 128, Title = "The Impact of Big Data on Businesses", Text = "nisl. Aenean lectus.", Description = "5 Tips for Effective Remote Work", UserId = 79, Tags = "AI,technology", PostingTime = new DateTime(2022, 5, 4) },
    new Post { Id = 129, Title = "How to Improve Your Coding Skills", Text = "hendrerit at", Description = "How AI is Revolutionizing Healthcare", UserId = 72, Tags = "digital,software", PostingTime = new DateTime(2023, 1, 22) },
    new Post { Id = 130, Title = "Digital Marketing Strategies for Success", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "5 Tips for Effective Remote Work", UserId = 56, Tags = "innovation,cybersecurity", PostingTime = new DateTime(2022, 6, 4) },
    new Post { Id = 131, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "consectetuer adipiscing elit.", Description = "Top 10 Tech Trends for 2021", UserId = 12, Tags = "AI,cybersecurity", PostingTime = new DateTime(2022, 12, 25) },
    new Post { Id = 132, Title = "Creating Engaging Content for Your Blog", Text = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.", Description = "5 Tips for Effective Remote Work", UserId = 62, Tags = "technology,digital", PostingTime = new DateTime(2024, 5, 21) },
    new Post { Id = 133, Title = "How AI is Revolutionizing the Tech Industry", Text = "consectetuer adipiscing elit.", Description = "The Future of Cybersecurity", UserId = 98, Tags = "coding,digital", PostingTime = new DateTime(2022, 10, 29) },
    new Post { Id = 134, Title = "SEO Strategies for Small Businesses", Text = "Vivamus metus arcu", Description = "The Future of Cybersecurity", UserId = 18, Tags = "technology,internet", PostingTime = new DateTime(2020, 2, 10) },
    new Post { Id = 135, Title = "Best Tools for Web Development", Text = "vulputate vitae", Description = "Blockchain Technology Explained", UserId = 39, Tags = "AI,cybersecurity", PostingTime = new DateTime(2023, 4, 2) },
    new Post { Id = 136, Title = "SEO Strategies for Small Businesses", Text = "lectus.", Description = "Top 10 Tech Trends for 2021", UserId = 87, Tags = "internet,technology", PostingTime = new DateTime(2020, 9, 29) },
    new Post { Id = 137, Title = "The Impact of Big Data on Businesses", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "Blockchain Technology Explained", UserId = 96, Tags = "AI,cybersecurity", PostingTime = new DateTime(2020, 3, 13) },
    new Post { Id = 138, Title = "Cybersecurity Tips for Beginners", Text = "aliquet at", Description = "Blockchain Technology Explained", UserId = 9, Tags = "innovation,technology", PostingTime = new DateTime(2021, 4, 20) },
    new Post { Id = 139, Title = "Blockchain Technology Explained", Text = "adipiscing molestie", Description = "The Future of Cybersecurity", UserId = 18, Tags = "software,coding", PostingTime = new DateTime(2023, 6, 3) },
    new Post { Id = 140, Title = "Top 10 Tech Trends of 2021", Text = "nascetur ridiculus mus.", Description = "The Future of Cybersecurity", UserId = 17, Tags = "internet,innovation", PostingTime = new DateTime(2021, 5, 13) },
    new Post { Id = 141, Title = "E-commerce Trends to Watch Out For", Text = "adipiscing molestie", Description = "5 Tips for Effective Remote Work", UserId = 31, Tags = "cybersecurity,digital", PostingTime = new DateTime(2020, 2, 12) },
    new Post { Id = 142, Title = "Creating Engaging Content for Your Blog", Text = "Integer pede justo", Description = "Top 10 Tech Trends for 2021", UserId = 77, Tags = "digital,technology", PostingTime = new DateTime(2022, 8, 15) },
    new Post { Id = 143, Title = "Cloud Computing Simplified", Text = "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.", Description = "How AI is Revolutionizing Healthcare", UserId = 13, Tags = "AI,data", PostingTime = new DateTime(2021, 9, 11) },
    new Post { Id = 144, Title = "Machine Learning Demystified", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "How AI is Revolutionizing Healthcare", UserId = 28, Tags = "internet,AI", PostingTime = new DateTime(2020, 7, 12) },
    new Post { Id = 145, Title = "Digital Marketing Strategies for Success", Text = "feugiat non", Description = "The Future of Cybersecurity", UserId = 79, Tags = "AI,cybersecurity", PostingTime = new DateTime(2021, 10, 4) },
    new Post { Id = 146, Title = "How to Improve Your Coding Skills", Text = "In blandit ultrices enim. Lorem ipsum dolor sit amet", Description = "Top 10 Tech Trends for 2021", UserId = 73, Tags = "technology,innovation", PostingTime = new DateTime(2020, 2, 8) },
    new Post { Id = 147, Title = "Cybersecurity in the Digital Age", Text = "feugiat non", Description = "Top 10 Tech Trends for 2021", UserId = 10, Tags = "technology,data", PostingTime = new DateTime(2022, 11, 13) },
    new Post { Id = 148, Title = "Top 10 Tech Trends of 2021", Text = "pretium quis", Description = "How AI is Revolutionizing Healthcare", UserId = 96, Tags = "innovation,digital", PostingTime = new DateTime(2023, 6, 22) },
    new Post { Id = 149, Title = "Data Privacy in the Digital Age", Text = "turpis nec euismod scelerisque", Description = "The Future of Cybersecurity", UserId = 42, Tags = "data,software", PostingTime = new DateTime(2023, 7, 22) },
    new Post { Id = 150, Title = "Creating Engaging Content for Your Blog", Text = "pede.", Description = "Blockchain Technology Explained", UserId = 85, Tags = "innovation,data", PostingTime = new DateTime(2022, 11, 14) },
    new Post { Id = 151, Title = "Cloud Computing Simplified", Text = "pretium quis", Description = "Top 10 Tech Trends for 2021", UserId = 30, Tags = "coding,internet", PostingTime = new DateTime(2021, 2, 23) },
    new Post { Id = 152, Title = "How AI is Revolutionizing the Tech Industry", Text = "vulputate vitae", Description = "5 Tips for Effective Remote Work", UserId = 40, Tags = "technology,coding", PostingTime = new DateTime(2022, 3, 6) },
    new Post { Id = 153, Title = "Cybersecurity Tips for Beginners", Text = "adipiscing molestie", Description = "5 Tips for Effective Remote Work", UserId = 15, Tags = "data,internet", PostingTime = new DateTime(2022, 8, 18) },
    new Post { Id = 154, Title = "Best Tools for Web Development", Text = "hendrerit at", Description = "Blockchain Technology Explained", UserId = 24, Tags = "data,cybersecurity", PostingTime = new DateTime(2024, 3, 5) },
    new Post { Id = 155, Title = "Cloud Computing Simplified", Text = "Cum sociis natoque penatibus et magnis dis parturient montes", Description = "Top 10 Tech Trends for 2021", UserId = 70, Tags = "AI,digital", PostingTime = new DateTime(2021, 3, 4) },
    new Post { Id = 156, Title = "How AI is Revolutionizing the Tech Industry", Text = "pede.", Description = "The Future of Cybersecurity", UserId = 7, Tags = "AI,internet", PostingTime = new DateTime(2021, 1, 21) },
    new Post { Id = 157, Title = "The Future of Virtual Reality", Text = "In blandit ultrices enim. Lorem ipsum dolor sit amet", Description = "Top 10 Tech Trends for 2021", UserId = 72, Tags = "software,technology", PostingTime = new DateTime(2021, 1, 7) },
    new Post { Id = 158, Title = "Cloud Computing Simplified", Text = "Integer pede justo", Description = "Blockchain Technology Explained", UserId = 47, Tags = "AI,cybersecurity", PostingTime = new DateTime(2023, 12, 22) },
    new Post { Id = 159, Title = "How AI is Revolutionizing the Tech Industry", Text = "Integer pede justo", Description = "The Future of Cybersecurity", UserId = 64, Tags = "innovation,coding", PostingTime = new DateTime(2023, 1, 5) },
    new Post { Id = 160, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "lectus.", Description = "5 Tips for Effective Remote Work", UserId = 93, Tags = "cybersecurity,digital", PostingTime = new DateTime(2024, 7, 12) },
    new Post { Id = 161, Title = "Innovations in Mobile App Development", Text = "adipiscing molestie", Description = "5 Tips for Effective Remote Work", UserId = 81, Tags = "software,coding", PostingTime = new DateTime(2024, 7, 30) },
    new Post { Id = 162, Title = "The Power of Influencer Marketing", Text = "Vivamus metus arcu", Description = "The Future of Cybersecurity", UserId = 13, Tags = "data,AI", PostingTime = new DateTime(2024, 9, 12) },
    new Post { Id = 163, Title = "Data Privacy in the Digital Age", Text = "feugiat non", Description = "5 Tips for Effective Remote Work", UserId = 84, Tags = "gadgets,digital", PostingTime = new DateTime(2020, 10, 10) },
    new Post { Id = 164, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "vulputate vitae", Description = "How AI is Revolutionizing Healthcare", UserId = 87, Tags = "coding,data", PostingTime = new DateTime(2022, 5, 26) },
    new Post { Id = 165, Title = "Cybersecurity Tips for Beginners", Text = "nisl.", Description = "Blockchain Technology Explained", UserId = 46, Tags = "cybersecurity,coding", PostingTime = new DateTime(2022, 6, 2) },
    new Post { Id = 166, Title = "Tech Gadgets Every Geek Should Have", Text = "In blandit ultrices enim. Lorem ipsum dolor sit amet", Description = "The Future of Cybersecurity", UserId = 81, Tags = "digital,gadgets", PostingTime = new DateTime(2021, 10, 30) },
    new Post { Id = 167, Title = "Cybersecurity in the Digital Age", Text = "aliquet at", Description = "How AI is Revolutionizing Healthcare", UserId = 59, Tags = "AI,technology", PostingTime = new DateTime(2022, 11, 14) },
    new Post { Id = 168, Title = "Best Tools for Web Development", Text = "nisl.", Description = "How AI is Revolutionizing Healthcare", UserId = 95, Tags = "technology,innovation", PostingTime = new DateTime(2023, 4, 19) },
    new Post { Id = 169, Title = "Blockchain Technology Explained", Text = "pretium quis", Description = "The Future of Cybersecurity", UserId = 75, Tags = "cybersecurity,gadgets", PostingTime = new DateTime(2020, 9, 20) },
    new Post { Id = 170, Title = "How to Improve Your Coding Skills", Text = "hendrerit at", Description = "5 Tips for Effective Remote Work", UserId = 10, Tags = "software,data", PostingTime = new DateTime(2023, 2, 24) },
    new Post { Id = 171, Title = "Digital Marketing Strategies for Success", Text = "pretium quis", Description = "5 Tips for Effective Remote Work", UserId = 62, Tags = "AI,technology", PostingTime = new DateTime(2021, 12, 10) },
    new Post { Id = 172, Title = "The Impact of Big Data on Businesses", Text = "pede.", Description = "The Future of Cybersecurity", UserId = 15, Tags = "data,gadgets", PostingTime = new DateTime(2024, 5, 23) },
    new Post { Id = 173, Title = "Cloud Computing Simplified", Text = "In blandit ultrices enim. Lorem ipsum dolor sit amet", Description = "5 Tips for Effective Remote Work", UserId = 23, Tags = "technology,internet", PostingTime = new DateTime(2021, 2, 27) },
    new Post { Id = 174, Title = "Cybersecurity in the Digital Age", Text = "feugiat non", Description = "The Future of Cybersecurity", UserId = 1, Tags = "data,AI", PostingTime = new DateTime(2024, 3, 16) },
    new Post { Id = 175, Title = "Cybersecurity in the Digital Age", Text = "nascetur ridiculus mus.", Description = "Blockchain Technology Explained", UserId = 50, Tags = "data,AI", PostingTime = new DateTime(2020, 8, 1) },
    new Post { Id = 176, Title = "The Future of Virtual Reality", Text = "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.", Description = "The Future of Cybersecurity", UserId = 35, Tags = "software,data", PostingTime = new DateTime(2023, 3, 7) },
    new Post { Id = 177, Title = "The Impact of Big Data on Businesses", Text = "adipiscing molestie", Description = "5 Tips for Effective Remote Work", UserId = 19, Tags = "AI,coding", PostingTime = new DateTime(2024, 4, 25) },
    new Post { Id = 178, Title = "The Future of Virtual Reality", Text = "lectus.", Description = "5 Tips for Effective Remote Work", UserId = 29, Tags = "digital,software", PostingTime = new DateTime(2023, 10, 28) },
    new Post { Id = 179, Title = "How to Improve Your Coding Skills", Text = "Vivamus metus arcu", Description = "Blockchain Technology Explained", UserId = 22, Tags = "coding,data", PostingTime = new DateTime(2022, 3, 8) },
    new Post { Id = 180, Title = "Blockchain Technology Explained", Text = "adipiscing molestie", Description = "Blockchain Technology Explained", UserId = 65, Tags = "cybersecurity,software", PostingTime = new DateTime(2024, 5, 3) },
    new Post { Id = 181, Title = "The Future of Virtual Reality", Text = "adipiscing molestie", Description = "The Future of Cybersecurity", UserId = 11, Tags = "AI,data", PostingTime = new DateTime(2022, 11, 22) },
    new Post { Id = 182, Title = "Top 10 Tech Trends of 2021", Text = "nascetur ridiculus mus.", Description = "Blockchain Technology Explained", UserId = 52, Tags = "digital,internet", PostingTime = new DateTime(2022, 2, 12) },
    new Post { Id = 183, Title = "How to Improve Your Coding Skills", Text = "vitae mattis nibh ligula nec sem.", Description = "5 Tips for Effective Remote Work", UserId = 20, Tags = "digital,gadgets", PostingTime = new DateTime(2022, 1, 10) },
    new Post { Id = 184, Title = "E-commerce Trends to Watch Out For", Text = "tincidunt eget", Description = "The Future of Cybersecurity", UserId = 58, Tags = "AI,digital", PostingTime = new DateTime(2023, 9, 8) },
    new Post { Id = 185, Title = "Cybersecurity Tips for Beginners", Text = "tincidunt eget", Description = "How AI is Revolutionizing Healthcare", UserId = 51, Tags = "gadgets,software", PostingTime = new DateTime(2021, 6, 9) },
    new Post { Id = 186, Title = "Top 10 Tech Trends for 2021", Text = "nisl.", Description = "5 Tips for Effective Remote Work", UserId = 38, Tags = "software,innovation", PostingTime = new DateTime(2024, 3, 14) },
    new Post { Id = 187, Title = "Cybersecurity in the Digital Age", Text = "quam turpis adipiscing lorem", Description = "Top 10 Tech Trends for 2021", UserId = 91, Tags = "innovation,internet", PostingTime = new DateTime(2020, 11, 11) },
    new Post { Id = 188, Title = "Cloud Computing Simplified", Text = "hendrerit at", Description = "Blockchain Technology Explained", UserId = 17, Tags = "AI,data", PostingTime = new DateTime(2023, 7, 14) },
    new Post { Id = 189, Title = "The Rise of Blockchain TechnologySEO Strategies for Small Businesses", Text = "nisl. Aenean lectus.", Description = "Top 10 Tech Trends for 2021", UserId = 62, Tags = "digital,technology", PostingTime = new DateTime(2022, 11, 25) },
    new Post { Id = 190, Title = "E-commerce Trends to Watch Out For", Text = "Vivamus metus arcu", Description = "Blockchain Technology Explained", UserId = 73, Tags = "technology,cybersecurity", PostingTime = new DateTime(2023, 7, 15) },
    new Post { Id = 191, Title = "Cloud Computing Simplified", Text = "consectetuer adipiscing elit.", Description = "5 Tips for Effective Remote Work", UserId = 4, Tags = "software,technology", PostingTime = new DateTime(2021, 7, 26) },
    new Post { Id = 192, Title = "The Future of Virtual Reality", Text = "lectus.", Description = "Blockchain Technology Explained", UserId = 50, Tags = "AI,innovation", PostingTime = new DateTime(2023, 8, 7) },
    new Post { Id = 193, Title = "Data Privacy in the Digital Age", Text = "hendrerit at", Description = "Blockchain Technology Explained", UserId = 16, Tags = "innovation,data", PostingTime = new DateTime(2021, 10, 11) },
    new Post { Id = 194, Title = "Top 10 Tech Trends of 2021", Text = "vulputate vitae", Description = "How AI is Revolutionizing Healthcare", UserId = 36, Tags = "internet,innovation", PostingTime = new DateTime(2024, 6, 18) },
    new Post { Id = 195, Title = "Cybersecurity in the Digital Age", Text = "Morbi quis tortor id nulla ultrices aliquet.", Description = "Top 10 Tech Trends for 2021", UserId = 20, Tags = "digital,internet", PostingTime = new DateTime(2023, 9, 27) },
    new Post { Id = 196, Title = "Machine Learning Demystified", Text = "Nulla ac enim. In tempor", Description = "5 Tips for Effective Remote Work", UserId = 62, Tags = "gadgets,AI", PostingTime = new DateTime(2021, 2, 10) },
    new Post { Id = 197, Title = "Cybersecurity in the Digital Age", Text = "hendrerit at", Description = "5 Tips for Effective Remote Work", UserId = 12, Tags = "AI,digital", PostingTime = new DateTime(2020, 4, 18) },
    new Post { Id = 198, Title = "Cloud Computing Simplified", Text = "adipiscing molestie", Description = "5 Tips for Effective Remote Work", UserId = 99, Tags = "software,digital", PostingTime = new DateTime(2020, 2, 28) },
    new Post { Id = 199, Title = "E-commerce Trends to Watch Out For", Text = "Vivamus metus arcu", Description = "Top 10 Tech Trends for 2021", UserId = 22, Tags = "coding,technology", PostingTime = new DateTime(2020, 9, 22) },
    new Post { Id = 200, Title = "Cloud Computing Simplified", Text = "vulputate vitae", Description = "How AI is Revolutionizing Healthcare", UserId = 59, Tags = "software,internet", PostingTime = new DateTime(2021, 10, 16) }
});
            #endregion

            #region StarData
            modelBuilder.Entity<Star>().HasData(new List<Star>
{
    new Star { Id = 1, UserId = 58, PostId = 113, Rating = 4 },
    new Star { Id = 2, UserId = 26, PostId = 140, Rating = 2 },
    new Star { Id = 3, UserId = 46, PostId = 68, Rating = 0 },
    new Star { Id = 4, UserId = 7, PostId = 80, Rating = 0 },
    new Star { Id = 5, UserId = 71, PostId = 122, Rating = 0 },
    new Star { Id = 6, UserId = 38, PostId = 83, Rating = 5 },
    new Star { Id = 7, UserId = 44, PostId = 142, Rating = 1 },
    new Star { Id = 8, UserId = 42, PostId = 31, Rating = 5 },
    new Star { Id = 9, UserId = 50, PostId = 86, Rating = 5 },
    new Star { Id = 10, UserId = 23, PostId = 55, Rating = 3 },
    new Star { Id = 11, UserId = 74, PostId = 24, Rating = 5 },
    new Star { Id = 12, UserId = 75, PostId = 139, Rating = 3 },
    new Star { Id = 13, UserId = 79, PostId = 53, Rating = 4 },
    new Star { Id = 14, UserId = 81, PostId = 157, Rating = 0 },
    new Star { Id = 15, UserId = 21, PostId = 193, Rating = 2 },
    new Star { Id = 16, UserId = 28, PostId = 169, Rating = 2 },
    new Star { Id = 17, UserId = 41, PostId = 36, Rating = 4 },
    new Star { Id = 18, UserId = 84, PostId = 7, Rating = 1 },
    new Star { Id = 19, UserId = 7, PostId = 58, Rating = 2 },
    new Star { Id = 20, UserId = 58, PostId = 118, Rating = 3 },
    new Star { Id = 21, UserId = 52, PostId = 140, Rating = 2 },
    new Star { Id = 22, UserId = 97, PostId = 1, Rating = 2 },
    new Star { Id = 23, UserId = 85, PostId = 87, Rating = 2 },
    new Star { Id = 24, UserId = 21, PostId = 27, Rating = 1 },
    new Star { Id = 25, UserId = 85, PostId = 168, Rating = 0 },
    new Star { Id = 26, UserId = 81, PostId = 119, Rating = 5 },
    new Star { Id = 27, UserId = 70, PostId = 68, Rating = 5 },
    new Star { Id = 28, UserId = 94, PostId = 128, Rating = 5 },
    new Star { Id = 29, UserId = 40, PostId = 86, Rating = 4 },
    new Star { Id = 30, UserId = 25, PostId = 57, Rating = 2 },
    new Star { Id = 31, UserId = 27, PostId = 175, Rating = 3 },
    new Star { Id = 32, UserId = 69, PostId = 170, Rating = 3 },
    new Star { Id = 33, UserId = 98, PostId = 58, Rating = 0 },
    new Star { Id = 34, UserId = 26, PostId = 181, Rating = 5 },
    new Star { Id = 35, UserId = 34, PostId = 155, Rating = 0 },
    new Star { Id = 36, UserId = 61, PostId = 30, Rating = 1 },
    new Star { Id = 37, UserId = 18, PostId = 18, Rating = 1 },
    new Star { Id = 38, UserId = 21, PostId = 137, Rating = 3 },
    new Star { Id = 39, UserId = 13, PostId = 125, Rating = 1 },
    new Star { Id = 40, UserId = 34, PostId = 65, Rating = 0 },
    new Star { Id = 41, UserId = 74, PostId = 61, Rating = 0 },
    new Star { Id = 42, UserId = 29, PostId = 87, Rating = 1 },
    new Star { Id = 43, UserId = 46, PostId = 87, Rating = 4 },
    new Star { Id = 44, UserId = 18, PostId = 89, Rating = 0 },
    new Star { Id = 45, UserId = 41, PostId = 105, Rating = 5 },
    new Star { Id = 46, UserId = 73, PostId = 120, Rating = 5 },
    new Star { Id = 47, UserId = 25, PostId = 58, Rating = 0 },
    new Star { Id = 48, UserId = 44, PostId = 9, Rating = 1 },
    new Star { Id = 49, UserId = 57, PostId = 77, Rating = 4 },
    new Star { Id = 50, UserId = 55, PostId = 39, Rating = 3 },
    new Star { Id = 51, UserId = 40, PostId = 15, Rating = 3 },
    new Star { Id = 52, UserId = 24, PostId = 159, Rating = 0 },
    new Star { Id = 53, UserId = 69, PostId = 107, Rating = 2 },
    new Star { Id = 54, UserId = 55, PostId = 35, Rating = 4 },
    new Star { Id = 55, UserId = 51, PostId = 87, Rating = 5 },
    new Star { Id = 56, UserId = 45, PostId = 163, Rating = 5 },
    new Star { Id = 57, UserId = 94, PostId = 102, Rating = 4 },
    new Star { Id = 58, UserId = 14, PostId = 10, Rating = 4 },
    new Star { Id = 59, UserId = 35, PostId = 106, Rating = 3 },
    new Star { Id = 60, UserId = 40, PostId = 78, Rating = 5 },
    new Star { Id = 61, UserId = 45, PostId = 74, Rating = 2 },
    new Star { Id = 62, UserId = 25, PostId = 143, Rating = 0 },
    new Star { Id = 63, UserId = 46, PostId = 154, Rating = 1 },
    new Star { Id = 64, UserId = 98, PostId = 139, Rating = 1 },
    new Star { Id = 65, UserId = 11, PostId = 141, Rating = 4 },
    new Star { Id = 66, UserId = 58, PostId = 175, Rating = 3 },
    new Star { Id = 67, UserId = 88, PostId = 148, Rating = 4 },
    new Star { Id = 68, UserId = 95, PostId = 63, Rating = 0 },
    new Star { Id = 69, UserId = 40, PostId = 55, Rating = 2 },
    new Star { Id = 70, UserId = 83, PostId = 96, Rating = 2 },
    new Star { Id = 71, UserId = 90, PostId = 82, Rating = 5 },
    new Star { Id = 72, UserId = 16, PostId = 112, Rating = 2 },
    new Star { Id = 73, UserId = 93, PostId = 31, Rating = 2 },
    new Star { Id = 74, UserId = 23, PostId = 95, Rating = 3 },
    new Star { Id = 75, UserId = 27, PostId = 82, Rating = 4 },
    new Star { Id = 76, UserId = 76, PostId = 139, Rating = 2 },
    new Star { Id = 77, UserId = 30, PostId = 81, Rating = 0 },
    new Star { Id = 78, UserId = 45, PostId = 116, Rating = 1 },
    new Star { Id = 79, UserId = 74, PostId = 49, Rating = 0 },
    new Star { Id = 80, UserId = 93, PostId = 90, Rating = 4 },
    new Star { Id = 81, UserId = 87, PostId = 140, Rating = 0 },
    new Star { Id = 82, UserId = 84, PostId = 14, Rating = 4 },
    new Star { Id = 83, UserId = 88, PostId = 41, Rating = 4 },
    new Star { Id = 84, UserId = 35, PostId = 25, Rating = 3 },
    new Star { Id = 85, UserId = 76, PostId = 155, Rating = 0 },
    new Star { Id = 86, UserId = 76, PostId = 24, Rating = 4 },
    new Star { Id = 87, UserId = 91, PostId = 168, Rating = 5 },
    new Star { Id = 88, UserId = 84, PostId = 192, Rating = 0 },
    new Star { Id = 89, UserId = 71, PostId = 190, Rating = 0 },
    new Star { Id = 90, UserId = 69, PostId = 114, Rating = 1 },
    new Star { Id = 91, UserId = 10, PostId = 15, Rating = 1 },
    new Star { Id = 92, UserId = 69, PostId = 16, Rating = 3 },
    new Star { Id = 93, UserId = 83, PostId = 110, Rating = 2 },
    new Star { Id = 94, UserId = 73, PostId = 78, Rating = 4 },
    new Star { Id = 95, UserId = 6, PostId = 124, Rating = 1 },
    new Star { Id = 96, UserId = 1, PostId = 80, Rating = 0 },
    new Star { Id = 97, UserId = 7, PostId = 18, Rating = 5 },
    new Star { Id = 98, UserId = 21, PostId = 48, Rating = 4 },
    new Star { Id = 99, UserId = 38, PostId = 196, Rating = 4 },
    new Star { Id = 100, UserId = 90, PostId = 85, Rating = 4 },
    new Star { Id = 101, UserId = 38, PostId = 23, Rating = 1 },
    new Star { Id = 102, UserId = 90, PostId = 137, Rating = 2 },
    new Star { Id = 103, UserId = 37, PostId = 126, Rating = 4 },
    new Star { Id = 104, UserId = 38, PostId = 62, Rating = 1 },
    new Star { Id = 105, UserId = 29, PostId = 149, Rating = 0 },
    new Star { Id = 106, UserId = 96, PostId = 26, Rating = 1 },
    new Star { Id = 107, UserId = 21, PostId = 18, Rating = 0 },
    new Star { Id = 108, UserId = 3, PostId = 120, Rating = 1 },
    new Star { Id = 109, UserId = 67, PostId = 10, Rating = 2 },
    new Star { Id = 110, UserId = 4, PostId = 68, Rating = 2 },
    new Star { Id = 111, UserId = 12, PostId = 138, Rating = 5 },
    new Star { Id = 112, UserId = 85, PostId = 67, Rating = 1 },
    new Star { Id = 113, UserId = 26, PostId = 133, Rating = 4 },
    new Star { Id = 114, UserId = 33, PostId = 5, Rating = 1 },
    new Star { Id = 115, UserId = 41, PostId = 8, Rating = 2 },
    new Star { Id = 116, UserId = 74, PostId = 141, Rating = 3 },
    new Star { Id = 117, UserId = 97, PostId = 79, Rating = 1 },
    new Star { Id = 118, UserId = 31, PostId = 162, Rating = 5 },
    new Star { Id = 119, UserId = 27, PostId = 148, Rating = 4 },
    new Star { Id = 120, UserId = 64, PostId = 148, Rating = 0 },
    new Star { Id = 121, UserId = 87, PostId = 26, Rating = 3 },
    new Star { Id = 122, UserId = 94, PostId = 67, Rating = 3 },
    new Star { Id = 123, UserId = 83, PostId = 198, Rating = 4 },
    new Star { Id = 124, UserId = 61, PostId = 104, Rating = 4 },
    new Star { Id = 125, UserId = 2, PostId = 32, Rating = 4 },
    new Star { Id = 126, UserId = 97, PostId = 10, Rating = 0 },
    new Star { Id = 127, UserId = 90, PostId = 169, Rating = 1 },
    new Star { Id = 128, UserId = 40, PostId = 187, Rating = 0 },
    new Star { Id = 129, UserId = 70, PostId = 66, Rating = 5 },
    new Star { Id = 130, UserId = 95, PostId = 132, Rating = 4 },
    new Star { Id = 131, UserId = 49, PostId = 15, Rating = 0 },
    new Star { Id = 132, UserId = 68, PostId = 182, Rating = 0 },
    new Star { Id = 133, UserId = 99, PostId = 48, Rating = 0 },
    new Star { Id = 134, UserId = 66, PostId = 185, Rating = 4 },
    new Star { Id = 135, UserId = 12, PostId = 138, Rating = 2 },
    new Star { Id = 136, UserId = 8, PostId = 35, Rating = 5 },
    new Star { Id = 137, UserId = 61, PostId = 52, Rating = 0 },
    new Star { Id = 138, UserId = 34, PostId = 126, Rating = 3 },
    new Star { Id = 139, UserId = 32, PostId = 123, Rating = 5 },
    new Star { Id = 140, UserId = 87, PostId = 124, Rating = 3 },
    new Star { Id = 141, UserId = 83, PostId = 124, Rating = 2 },
    new Star { Id = 142, UserId = 100, PostId = 185, Rating = 2 },
    new Star { Id = 143, UserId = 47, PostId = 85, Rating = 0 },
    new Star { Id = 144, UserId = 7, PostId = 13, Rating = 0 },
    new Star { Id = 145, UserId = 91, PostId = 43, Rating = 1 },
    new Star { Id = 146, UserId = 13, PostId = 68, Rating = 1 },
    new Star { Id = 147, UserId = 34, PostId = 34, Rating = 5 },
    new Star { Id = 148, UserId = 35, PostId = 103, Rating = 1 },
    new Star { Id = 149, UserId = 78, PostId = 194, Rating = 3 },
    new Star { Id = 150, UserId = 59, PostId = 44, Rating = 0 },
    new Star { Id = 151, UserId = 70, PostId = 154, Rating = 0 },
    new Star { Id = 152, UserId = 100, PostId = 107, Rating = 2 },
    new Star { Id = 153, UserId = 61, PostId = 40, Rating = 2 },
    new Star { Id = 154, UserId = 22, PostId = 145, Rating = 1 },
    new Star { Id = 155, UserId = 22, PostId = 126, Rating = 0 },
    new Star { Id = 156, UserId = 4, PostId = 23, Rating = 3 },
    new Star { Id = 157, UserId = 56, PostId = 62, Rating = 5 },
    new Star { Id = 158, UserId = 3, PostId = 14, Rating = 3 },
    new Star { Id = 159, UserId = 48, PostId = 74, Rating = 5 },
    new Star { Id = 160, UserId = 24, PostId = 16, Rating = 1 },
    new Star { Id = 161, UserId = 66, PostId = 2, Rating = 0 },
    new Star { Id = 162, UserId = 1, PostId = 104, Rating = 5 },
    new Star { Id = 163, UserId = 13, PostId = 106, Rating = 0 },
    new Star { Id = 164, UserId = 53, PostId = 67, Rating = 3 },
    new Star { Id = 165, UserId = 32, PostId = 135, Rating = 1 },
    new Star { Id = 166, UserId = 24, PostId = 52, Rating = 3 },
    new Star { Id = 167, UserId = 22, PostId = 188, Rating = 2 },
    new Star { Id = 168, UserId = 41, PostId = 23, Rating = 1 },
    new Star { Id = 169, UserId = 57, PostId = 168, Rating = 3 },
    new Star { Id = 170, UserId = 82, PostId = 182, Rating = 0 },
    new Star { Id = 171, UserId = 69, PostId = 152, Rating = 0 },
    new Star { Id = 172, UserId = 52, PostId = 169, Rating = 1 },
    new Star { Id = 173, UserId = 71, PostId = 171, Rating = 4 },
    new Star { Id = 174, UserId = 66, PostId = 60, Rating = 2 },
    new Star { Id = 175, UserId = 80, PostId = 47, Rating = 0 },
    new Star { Id = 176, UserId = 27, PostId = 57, Rating = 1 },
    new Star { Id = 177, UserId = 38, PostId = 78, Rating = 4 },
    new Star { Id = 178, UserId = 37, PostId = 169, Rating = 5 },
    new Star { Id = 179, UserId = 24, PostId = 177, Rating = 3 },
    new Star { Id = 180, UserId = 67, PostId = 147, Rating = 1 },
    new Star { Id = 181, UserId = 99, PostId = 67, Rating = 2 },
    new Star { Id = 182, UserId = 52, PostId = 60, Rating = 4 },
    new Star { Id = 183, UserId = 99, PostId = 49, Rating = 1 },
    new Star { Id = 184, UserId = 8, PostId = 190, Rating = 1 },
    new Star { Id = 185, UserId = 49, PostId = 2, Rating = 3 },
    new Star { Id = 186, UserId = 64, PostId = 47, Rating = 5 },
    new Star { Id = 187, UserId = 19, PostId = 77, Rating = 4 },
    new Star { Id = 188, UserId = 41, PostId = 167, Rating = 5 },
    new Star { Id = 189, UserId = 99, PostId = 65, Rating = 2 },
    new Star { Id = 190, UserId = 11, PostId = 148, Rating = 5 },
    new Star { Id = 191, UserId = 19, PostId = 121, Rating = 3 },
    new Star { Id = 192, UserId = 13, PostId = 55, Rating = 4 },
    new Star { Id = 193, UserId = 33, PostId = 93, Rating = 4 },
    new Star { Id = 194, UserId = 37, PostId = 20, Rating = 4 },
    new Star { Id = 195, UserId = 29, PostId = 51, Rating = 3 },
    new Star { Id = 196, UserId = 25, PostId = 196, Rating = 4 },
    new Star { Id = 197, UserId = 44, PostId = 94, Rating = 3 },
    new Star { Id = 198, UserId = 88, PostId = 100, Rating = 4 },
    new Star { Id = 199, UserId = 67, PostId = 194, Rating = 3 },
    new Star { Id = 200, UserId = 79, PostId = 166, Rating = 1 }
});
            #endregion

            modelBuilder.Entity<NewsLetter>()
                .HasKey(x => x.Email);

            modelBuilder.Entity<Star>()
                .HasOne(m => m.User)  
                .WithMany(u => u.Stars)  
                .HasForeignKey(m => m.UserId)
                .OnDelete(DeleteBehavior.Restrict);

            //modelBuilder.Entity<Star>()
            //    .HasOne(m => m.Post)
            //    .WithMany(u => u.Stars)
            //    .HasForeignKey(m => m.UserId)
            //    .OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<User>()
                .HasMany(x => x.Stars)
                .WithOne(u => u.User)
                .HasForeignKey(i  => i.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<User>()
               .HasMany(x => x.Posts)
               .WithOne(u => u.User)
               .HasForeignKey(i => i.UserId)
               .OnDelete(DeleteBehavior.Cascade);

        }

    }
}